// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package interfacestest

import (
	"io"
	"sync"

	"github.com/ONSdigital/dis-design-system-go/model"
	"github.com/ONSdigital/dp-frontend-feedback-controller/interfaces"
)

var (
	lockRendererMockBuildPage        sync.RWMutex
	lockRendererMockNewBasePageModel sync.RWMutex
)

// Ensure, that RendererMock does implement interfaces.Renderer.
// If this is not the case, regenerate this file with moq.
var _ interfaces.Renderer = &RendererMock{}

// RendererMock is a mock implementation of interfaces.Renderer.
//
//	    func TestSomethingThatUsesRenderer(t *testing.T) {
//
//	        // make and configure a mocked interfaces.Renderer
//	        mockedRenderer := &RendererMock{
//	            BuildPageFunc: func(w io.Writer, pageModel interface{}, templateName string)  {
//		               panic("mock out the BuildPage method")
//	            },
//	            NewBasePageModelFunc: func() model.Page {
//		               panic("mock out the NewBasePageModel method")
//	            },
//	        }
//
//	        // use mockedRenderer in code that requires interfaces.Renderer
//	        // and then make assertions.
//
//	    }
type RendererMock struct {
	// BuildPageFunc mocks the BuildPage method.
	BuildPageFunc func(w io.Writer, pageModel interface{}, templateName string)

	// NewBasePageModelFunc mocks the NewBasePageModel method.
	NewBasePageModelFunc func() model.Page

	// calls tracks calls to the methods.
	calls struct {
		// BuildPage holds details about calls to the BuildPage method.
		BuildPage []struct {
			// W is the w argument value.
			W io.Writer
			// PageModel is the pageModel argument value.
			PageModel interface{}
			// TemplateName is the templateName argument value.
			TemplateName string
		}
		// NewBasePageModel holds details about calls to the NewBasePageModel method.
		NewBasePageModel []struct {
		}
	}
}

// BuildPage calls BuildPageFunc.
func (mock *RendererMock) BuildPage(w io.Writer, pageModel interface{}, templateName string) {
	if mock.BuildPageFunc == nil {
		panic("RendererMock.BuildPageFunc: method is nil but Renderer.BuildPage was just called")
	}
	callInfo := struct {
		W            io.Writer
		PageModel    interface{}
		TemplateName string
	}{
		W:            w,
		PageModel:    pageModel,
		TemplateName: templateName,
	}
	lockRendererMockBuildPage.Lock()
	mock.calls.BuildPage = append(mock.calls.BuildPage, callInfo)
	lockRendererMockBuildPage.Unlock()
	mock.BuildPageFunc(w, pageModel, templateName)
}

// BuildPageCalls gets all the calls that were made to BuildPage.
// Check the length with:
//
//	len(mockedRenderer.BuildPageCalls())
func (mock *RendererMock) BuildPageCalls() []struct {
	W            io.Writer
	PageModel    interface{}
	TemplateName string
} {
	var calls []struct {
		W            io.Writer
		PageModel    interface{}
		TemplateName string
	}
	lockRendererMockBuildPage.RLock()
	calls = mock.calls.BuildPage
	lockRendererMockBuildPage.RUnlock()
	return calls
}

// NewBasePageModel calls NewBasePageModelFunc.
func (mock *RendererMock) NewBasePageModel() model.Page {
	if mock.NewBasePageModelFunc == nil {
		panic("RendererMock.NewBasePageModelFunc: method is nil but Renderer.NewBasePageModel was just called")
	}
	callInfo := struct {
	}{}
	lockRendererMockNewBasePageModel.Lock()
	mock.calls.NewBasePageModel = append(mock.calls.NewBasePageModel, callInfo)
	lockRendererMockNewBasePageModel.Unlock()
	return mock.NewBasePageModelFunc()
}

// NewBasePageModelCalls gets all the calls that were made to NewBasePageModel.
// Check the length with:
//
//	len(mockedRenderer.NewBasePageModelCalls())
func (mock *RendererMock) NewBasePageModelCalls() []struct {
} {
	var calls []struct {
	}
	lockRendererMockNewBasePageModel.RLock()
	calls = mock.calls.NewBasePageModel
	lockRendererMockNewBasePageModel.RUnlock()
	return calls
}
